<a href="https://colab.research.google.com/github/enigma6174/tensorflow-learn/blob/develop/fundamentals/indexing_and_manipulation.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import tensorflow as tf
import numpy as np

# Working With Tensors



*   Indexing And Expanding 
*   Manipulating With Basic Operations




## [1] Indexing And Expanding

In [2]:
tensor = tf.constant([
    [
      [1, 2, 3],
      [5, 6, 7],
      [9, 10, 11],
      [-1, -2, -3]
    ],
    [
      [10, 20, 30],
      [50, 60, 70],
      [19, 110, 111],
      [-1, -2, -3]
    ],
    [
      [105, 207, 390],
      [5034, 608, 7560],
      [1569, 11230, 1711],
      [-1, -20, -3]
    ]
], dtype=tf.int32)
tensor

<tf.Tensor: shape=(3, 4, 3), dtype=int32, numpy=
array([[[    1,     2,     3],
        [    5,     6,     7],
        [    9,    10,    11],
        [   -1,    -2,    -3]],

       [[   10,    20,    30],
        [   50,    60,    70],
        [   19,   110,   111],
        [   -1,    -2,    -3]],

       [[  105,   207,   390],
        [ 5034,   608,  7560],
        [ 1569, 11230,  1711],
        [   -1,   -20,    -3]]], dtype=int32)>

In [3]:
# get the first two elements from axis 0 
tensor[:2]

<tf.Tensor: shape=(2, 4, 3), dtype=int32, numpy=
array([[[  1,   2,   3],
        [  5,   6,   7],
        [  9,  10,  11],
        [ -1,  -2,  -3]],

       [[ 10,  20,  30],
        [ 50,  60,  70],
        [ 19, 110, 111],
        [ -1,  -2,  -3]]], dtype=int32)>

In [4]:
# get the first two elements from axis 0 and axis 1
tensor[:2, :2]

<tf.Tensor: shape=(2, 2, 3), dtype=int32, numpy=
array([[[ 1,  2,  3],
        [ 5,  6,  7]],

       [[10, 20, 30],
        [50, 60, 70]]], dtype=int32)>

In [5]:
# get the first two elements from axis 1 for all items in axis 0
tensor[:3, :2]

<tf.Tensor: shape=(3, 2, 3), dtype=int32, numpy=
array([[[   1,    2,    3],
        [   5,    6,    7]],

       [[  10,   20,   30],
        [  50,   60,   70]],

       [[ 105,  207,  390],
        [5034,  608, 7560]]], dtype=int32)>

In [6]:
# get the first three elements from axis 2
# corresponding to second element of axis 1 and second element of axis 0
tensor[1, 1, :3]

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([50, 60, 70], dtype=int32)>

In [7]:
# get the last two elements from axis 2
# corresponding to second element of axis 1 and third element of axis 0
tensor[2, 1, 1:]

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([ 608, 7560], dtype=int32)>

In [8]:
# get the last two elements from axis 2
# corresponding to all elements of axis 1 starting from the second element
# corresponding to the third element of axis 0
tensor[2, 1:, 1:]

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[  608,  7560],
       [11230,  1711],
       [  -20,    -3]], dtype=int32)>

In [9]:
# get the first 2 elements from axis 2
# corresponding to last 3 elements of every element of axis 1
# corresponding to every element of axis 0
tensor[:3, 1:, :2]

<tf.Tensor: shape=(3, 3, 2), dtype=int32, numpy=
array([[[    5,     6],
        [    9,    10],
        [   -1,    -2]],

       [[   50,    60],
        [   19,   110],
        [   -1,    -2]],

       [[ 5034,   608],
        [ 1569, 11230],
        [   -1,   -20]]], dtype=int32)>

In [10]:
# get the first two elements of each dimension
tensor[:2, :2, :2]

<tf.Tensor: shape=(2, 2, 2), dtype=int32, numpy=
array([[[ 1,  2],
        [ 5,  6]],

       [[10, 20],
        [50, 60]]], dtype=int32)>

In [11]:
# get all the first columns
tensor[:, :, 0]

<tf.Tensor: shape=(3, 4), dtype=int32, numpy=
array([[   1,    5,    9,   -1],
       [  10,   50,   19,   -1],
       [ 105, 5034, 1569,   -1]], dtype=int32)>

In [12]:
# get all the first rows
tensor[:, 0, :]

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[  1,   2,   3],
       [ 10,  20,  30],
       [105, 207, 390]], dtype=int32)>

In [13]:
rank_2_tensor = tf.constant([
    [11, 13],
    [23, 29]
])
rank_2_tensor.shape, rank_2_tensor.ndim

(TensorShape([2, 2]), 2)

In [14]:
rank_2_tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[11, 13],
       [23, 29]], dtype=int32)>

In [15]:
# get the last item of each axis
rank_2_tensor[:, -1]

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([13, 29], dtype=int32)>

In [16]:
# add an extra dimension with tf.newaxis
rank_3_tensor = rank_2_tensor[..., tf.newaxis]
rank_3_tensor.shape, rank_3_tensor.ndim

(TensorShape([2, 2, 1]), 3)

In [17]:
rank_3_tensor

<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[11],
        [13]],

       [[23],
        [29]]], dtype=int32)>

In [18]:
some_tensor = tf.constant([
    [1, 2, 3, 4],
    [5, 6, 7, 8],
    [9, 10, 11, 12]
])
some_tensor.shape, some_tensor.ndim

(TensorShape([3, 4]), 2)

In [19]:
some_tensor

<tf.Tensor: shape=(3, 4), dtype=int32, numpy=
array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]], dtype=int32)>

In [20]:
another_tensor = some_tensor[..., tf.newaxis]
another_tensor.shape, another_tensor.ndim

(TensorShape([3, 4, 1]), 3)

In [21]:
another_tensor

<tf.Tensor: shape=(3, 4, 1), dtype=int32, numpy=
array([[[ 1],
        [ 2],
        [ 3],
        [ 4]],

       [[ 5],
        [ 6],
        [ 7],
        [ 8]],

       [[ 9],
        [10],
        [11],
        [12]]], dtype=int32)>

In [22]:
rank_2_tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[11, 13],
       [23, 29]], dtype=int32)>

In [23]:
# tf.expand_dims() is an alternative to tf.newaxis
rank_3_tensor = tf.expand_dims(rank_2_tensor, axis=-1)
rank_3_tensor.shape, rank_3_tensor.ndim

(TensorShape([2, 2, 1]), 3)

In [24]:
# we can expand the dim along any axis
rank_3_tensor = tf.expand_dims(rank_2_tensor, axis=0)
rank_3_tensor.shape, rank_3_tensor.ndim

(TensorShape([1, 2, 2]), 3)

In [25]:
rank_3_tensor

<tf.Tensor: shape=(1, 2, 2), dtype=int32, numpy=
array([[[11, 13],
        [23, 29]]], dtype=int32)>

## [2] Manipulating Tensors With Basic Operations

Prefer in-built tensorflow libraries over operator use for manipulation operations because the tensorflow libraries are GPU optimised

In [26]:
tensor = tf.constant([
    [11, 13, 17],
    [19, 23, 29],
])
tensor

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[11, 13, 17],
       [19, 23, 29]], dtype=int32)>

In [27]:
# add value to tensor
tensor + 100

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[111, 113, 117],
       [119, 123, 129]], dtype=int32)>

In [28]:
# subract vale from tensor
tensor - 10

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[ 1,  3,  7],
       [ 9, 13, 19]], dtype=int32)>

In [29]:
# multiply tensor by value
tensor * 0

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[0, 0, 0],
       [0, 0, 0]], dtype=int32)>

In [30]:
# divide tensor by value
tensor / 2

<tf.Tensor: shape=(2, 3), dtype=float64, numpy=
array([[ 5.5,  6.5,  8.5],
       [ 9.5, 11.5, 14.5]])>

In [31]:
tensor1 = tf.constant([
    [10, 20],
    [30, 40]
])

tensor2 = tf.constant([
    [1, 2],
    [3, 4]
])

tensor1, tensor2

(<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
 array([[10, 20],
        [30, 40]], dtype=int32)>, <tf.Tensor: shape=(2, 2), dtype=int32, numpy=
 array([[1, 2],
        [3, 4]], dtype=int32)>)

In [32]:
# add two tensors
tensor1 + tensor2

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[11, 22],
       [33, 44]], dtype=int32)>

In [33]:
# subtract two tensors
tensor1 - tensor2

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 9, 18],
       [27, 36]], dtype=int32)>

In [34]:
# elementwise multiplication of tensors
tensor1 * tensor2

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 10,  40],
       [ 90, 160]], dtype=int32)>

In [35]:
# elementwise division of tensors
tensor1 / tensor2

<tf.Tensor: shape=(2, 2), dtype=float64, numpy=
array([[10., 10.],
       [10., 10.]])>

In [37]:
tensor1, tensor2

(<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
 array([[10, 20],
        [30, 40]], dtype=int32)>, <tf.Tensor: shape=(2, 2), dtype=int32, numpy=
 array([[1, 2],
        [3, 4]], dtype=int32)>)

In [36]:
# add two tensors with tf.math.add()
tf.math.add(tensor1, tensor2)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[11, 22],
       [33, 44]], dtype=int32)>

In [38]:
# subtract second tensor from first tensor with tf.math.subtract()
tf.math.subtract(tensor1, tensor2)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 9, 18],
       [27, 36]], dtype=int32)>

In [39]:
# elementwise matrix multiplication with tf.math.multiply()
tf.math.multiply(tensor1, tensor2)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 10,  40],
       [ 90, 160]], dtype=int32)>

In [40]:
# elementwise matrix division with tf.math.divide()
tf.math.divide(tensor1, tensor2)

<tf.Tensor: shape=(2, 2), dtype=float64, numpy=
array([[10., 10.],
       [10., 10.]])>