<a href="https://colab.research.google.com/github/enigma6174/tensorflow-learn/blob/develop/fundamentals/matrix_multiplication.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import tensorflow as tf
import numpy as np

In [12]:
# tensor of shape (2, 2)
tensor_1 = tf.constant([
    [10, 14],
    [12, 9]
])

# tensor of shape (2, 2)
tensor_2 = tf.constant([
    [6, 7],
    [2, 3]
])

tensor_1, tensor_2

(<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
 array([[10, 14],
        [12,  9]], dtype=int32)>, <tf.Tensor: shape=(2, 2), dtype=int32, numpy=
 array([[6, 7],
        [2, 3]], dtype=int32)>)

# Dot Product Multiplication

The dot product of a matrix **A** and shape **(i, j)** with a matrix **B** and shape **(j, k)** is a matrix with shape **(i, k)**.  

There are two methods available two perform the dot product of two matrices:

- `tf.linalg.matmul()`
- `tf.tensordot()`

## [1] Multiplication With `tf.linalg.matmul()`

In [13]:
# matrix multiplication - resulting shape is (2, 2)
tf.linalg.matmul(tensor_1, tensor_2)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 88, 112],
       [ 90, 111]], dtype=int32)>

In [14]:
# tensor of shape (2, 3)
tensor_1 = tf.constant([
    [1, 2, 3],
    [4, 5, 6]
])

# tensor of shape (3, 2)
tensor_2 = tf.constant([
    [10, 1],
    [20, 2],
    [30, 3]
])

tensor_1, tensor_2

(<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
 array([[1, 2, 3],
        [4, 5, 6]], dtype=int32)>,
 <tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[10,  1],
        [20,  2],
        [30,  3]], dtype=int32)>)

In [15]:
# matric multiplication - resulting shape is (2, 2)
tf.linalg.matmul(tensor_1, tensor_2)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[140,  14],
       [320,  32]], dtype=int32)>

In [16]:
# tensor of shape (3, 1)
tensor_1 = tf.constant([
    [1],
    [2],
    [3]
])

# tensor of shape (1, 3)
tensor_2 = tf.constant([
    [10, 20, 30]
])

tensor_1, tensor_2

(<tf.Tensor: shape=(3, 1), dtype=int32, numpy=
 array([[1],
        [2],
        [3]], dtype=int32)>,
 <tf.Tensor: shape=(1, 3), dtype=int32, numpy=array([[10, 20, 30]], dtype=int32)>)

In [17]:
# matrix multiplication - resulting shape is (3, 3)
tf.linalg.matmul(tensor_1, tensor_2)

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[10, 20, 30],
       [20, 40, 60],
       [30, 60, 90]], dtype=int32)>

In [18]:
# tensor of shape (3, 2)
tensor_1 = tf.constant([
    [1, 3],
    [2, 2],
    [3, 1]
])

# tensor of shape (2, 3)
tensor_2 = tf.constant([
    [10, 20, 30],
    [1, 2, 3]
])

tensor_1, tensor_2

(<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[1, 3],
        [2, 2],
        [3, 1]], dtype=int32)>, <tf.Tensor: shape=(2, 3), dtype=int32, numpy=
 array([[10, 20, 30],
        [ 1,  2,  3]], dtype=int32)>)

In [19]:
# matrix multiplication - resulting shape is (3, 3)
tf.linalg.matmul(tensor_1, tensor_2)

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[13, 26, 39],
       [22, 44, 66],
       [31, 62, 93]], dtype=int32)>

In [20]:
# tensor of shape (2, 3)
tensor_1 = tf.constant([
    [1, 2, 3],
    [3, 2, 1]
])

# tensor of shape (2, 3)
tensor_2 = tf.constant([
    [10, 20, 30],
    [1, 2, 3]
])

tensor_1, tensor_2

(<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
 array([[1, 2, 3],
        [3, 2, 1]], dtype=int32)>,
 <tf.Tensor: shape=(2, 3), dtype=int32, numpy=
 array([[10, 20, 30],
        [ 1,  2,  3]], dtype=int32)>)

In [21]:
# matrix multiplication of two tensors of same shape not possible
try:
  tf.linalg.matmul(tensor_1, tensor_2)
except Exception as e:
  print(e)

Matrix size-incompatible: In[0]: [2,3], In[1]: [2,3] [Op:MatMul]


## Multiplication With `tf.tensordot()`

In [70]:
tensor_1 = tf.constant([
    [1, 2, 3],
    [4, 5, 6],
])

tensor_2 = tf.constant([
    [11, 12],
    [13, 14],
    [15, 16]
])

tensor_1, tensor_2

(<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
 array([[1, 2, 3],
        [4, 5, 6]], dtype=int32)>,
 <tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[11, 12],
        [13, 14],
        [15, 16]], dtype=int32)>)

In [74]:
# tensor multiplication with tf.tensordot() and axes=1
tf.tensordot(tensor_1, tensor_2, axes=1)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 82,  88],
       [199, 214]], dtype=int32)>

In [76]:
# tensor multiplication with tf.tensordot() and axes=0
tf.tensordot(tensor_1, tensor_2, axes=0)

<tf.Tensor: shape=(2, 3, 3, 2), dtype=int32, numpy=
array([[[[11, 12],
         [13, 14],
         [15, 16]],

        [[22, 24],
         [26, 28],
         [30, 32]],

        [[33, 36],
         [39, 42],
         [45, 48]]],


       [[[44, 48],
         [52, 56],
         [60, 64]],

        [[55, 60],
         [65, 70],
         [75, 80]],

        [[66, 72],
         [78, 84],
         [90, 96]]]], dtype=int32)>

# Altering The Shape Of A Tensor With `tf.reshape()`

`tf.reshape()` allows us to reshape the structure of the tensor to any shape. It must be noted that the size of the tensor before and after the reshape must remain the same, i.e. if the initial shape of the tensor is **(i, j, k)** and the final shape of the tensor is **(x, y, z)** then $(i*j*k) = (x*y*z)$

In [48]:
# tensor of shape (2, 3)
tensor = tf.constant([
    [11, 23, 37],
    [19, 67, 83]
])
tensor

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[11, 23, 37],
       [19, 67, 83]], dtype=int32)>

In [49]:
# change the shape of tensor to (3, 2)
tf.reshape(tensor, [3, 2])

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[11, 23],
       [37, 19],
       [67, 83]], dtype=int32)>

In [50]:
# change the shape of tensor to (6, 1)
tf.reshape(tensor, [6, 1])

<tf.Tensor: shape=(6, 1), dtype=int32, numpy=
array([[11],
       [23],
       [37],
       [19],
       [67],
       [83]], dtype=int32)>

In [51]:
# change the shape of tensor to (1, 6)
tf.reshape(tensor, [1, 6])

<tf.Tensor: shape=(1, 6), dtype=int32, numpy=array([[11, 23, 37, 19, 67, 83]], dtype=int32)>

In [56]:
# tensor of shape (4, 3) initialized with random numbers
tensor = tf.math.round(tf.math.multiply(tf.random.Generator.from_seed(42).normal(shape=(4, 3)), 100))
tensor

<tf.Tensor: shape=(4, 3), dtype=float32, numpy=
array([[ -76.,   -7.,    8.],
       [-126.,  -23., -181.],
       [  10.,  -51.,  -75.],
       [ -57.,   15.,  -23.]], dtype=float32)>

In [57]:
# reshape the tensor to (3, 2, 2)
tf.reshape(tensor, [3, 2, 2])

<tf.Tensor: shape=(3, 2, 2), dtype=float32, numpy=
array([[[ -76.,   -7.],
        [   8., -126.]],

       [[ -23., -181.],
        [  10.,  -51.]],

       [[ -75.,  -57.],
        [  15.,  -23.]]], dtype=float32)>

In [58]:
# reshape the tensor to (6, 2)
tf.reshape(tensor, [6, 2])

<tf.Tensor: shape=(6, 2), dtype=float32, numpy=
array([[ -76.,   -7.],
       [   8., -126.],
       [ -23., -181.],
       [  10.,  -51.],
       [ -75.,  -57.],
       [  15.,  -23.]], dtype=float32)>

In [59]:
# reshape the tensor to (2, 6, 1)
tf.reshape(tensor, [2, 6, 1])

<tf.Tensor: shape=(2, 6, 1), dtype=float32, numpy=
array([[[ -76.],
        [  -7.],
        [   8.],
        [-126.],
        [ -23.],
        [-181.]],

       [[  10.],
        [ -51.],
        [ -75.],
        [ -57.],
        [  15.],
        [ -23.]]], dtype=float32)>

# Altering The Shape Of A Tensor With `tf.transpose()`

Transposing a tensor means to flip it's dimensions. For example if the shape of a tensor is **(3, 2)** then after transpose, the shape of the tensor will be **(2, 3)**. 

In [65]:
# tensor of shape (2, 3) initialized with random numbers
tensor = tf.math.round(tf.math.multiply(tf.random.Generator.from_seed(42).normal(shape=(2, 3)), 100))
tensor

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[ -76.,   -7.,    8.],
       [-126.,  -23., -181.]], dtype=float32)>

In [66]:
# transpose the tensor
tf.transpose(tensor)

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[ -76., -126.],
       [  -7.,  -23.],
       [   8., -181.]], dtype=float32)>

In [67]:
# tensor of shape (2, 3, 2)
tensor = tf.constant([
    [
      [3, 5],
      [7, 11],
      [13, 19]
    ],
    [
      [47, 53],
      [57, 59],
      [61, 67]
    ]
])
tensor

<tf.Tensor: shape=(2, 3, 2), dtype=int32, numpy=
array([[[ 3,  5],
        [ 7, 11],
        [13, 19]],

       [[47, 53],
        [57, 59],
        [61, 67]]], dtype=int32)>

In [68]:
# transpose the tensor
tf.transpose(tensor)

<tf.Tensor: shape=(2, 3, 2), dtype=int32, numpy=
array([[[ 3, 47],
        [ 7, 57],
        [13, 61]],

       [[ 5, 53],
        [11, 59],
        [19, 67]]], dtype=int32)>