<a href="https://colab.research.google.com/github/enigma6174/tensorflow-learn/blob/develop/fundamentals/practice.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import tensorflow as tf
import numpy as np

In [3]:
# check the tensorflow version
tf.__version__

'2.9.2'

# Introduction To Tensors

#### Shape  
The length (number of elements) of each of the dimensions of a tensor.
A matrix with 2 rows and 5 columns will have the shape (2, 5) whereas a matrix with 3 rows and 1 column will have the shape (3, 1)  

It is accessed via `tensor.shape` 

#### Rank
The number of tensor dimensions. A scalar has a rank 0, a vector has a rank 1, matrix has a rank 2 and a tensor has a rank **n**  
A scalar is a tensor with **n=0** and a vector is a tensor with **n=1**  

It is accessed via `tensor.ndim`

#### Dimension
This refers to the particular dimension of the tensor. For a vector it will be `tensor[0]` and for a matrix it will be `tensor[0]` and `tensor[1]`. For a tensor of n-dimensions the values will be `tensor[0]`, `tensor[1]`, ... , `tensor[n-1]`  

#### Size
The total number of items in the tensor. It can be calculated by multiplying the values in the `tensor.shape` property. For example if the shape of a tensor is **(2, 3, 4)** then the size of the tensor will be **2x3x4 = 24** elements.  

# The size property of a tensor can be accessed via `tf.size(tensor)`

## [1] Creating Tensors With `tf.constant()`

In [7]:
# create a new tensor with no dimenstions
scalar = tf.constant(7)
scalar

<tf.Tensor: shape=(), dtype=float32, numpy=7.0>

In [9]:
# check the dimensions of the tensor
scalar.ndim

0

In [10]:
# create a tensor with one dimension
vector = tf.constant([10, 2])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10,  2], dtype=int32)>

In [20]:
# check the dimension of the tensor
vector.ndim

1

In [12]:
# create a tensor with 2 dimensions
matrix = tf.constant([
    [10, 20],
    [4, 5],
    [3, 1],
    [99, -100]
])
matrix

<tf.Tensor: shape=(4, 2), dtype=int32, numpy=
array([[  10,   20],
       [   4,    5],
       [   3,    1],
       [  99, -100]], dtype=int32)>

In [21]:
# check the dimensions
matrix.ndim

2

In [22]:
# create a tensor with 2 dimensions and float16 dtype
another_matrix = tf.constant([
    [7., 3., 1.],
    [3., 99., 11.]
], dtype=tf.float16)
another_matrix

<tf.Tensor: shape=(2, 3), dtype=float16, numpy=
array([[ 7.,  3.,  1.],
       [ 3., 99., 11.]], dtype=float16)>

In [23]:
# check the dimensions
another_matrix.ndim

2

In [24]:
# create a tensor with 3 dimensions
# for this example the tensor can be visualized as 2 matrices of shape (3, 4)
# the inner dimensions of every structure must be the same
tensor = tf.constant([
    [
      [1, 2, 3, 4],
      [10, 20, 30, 40],
      [1, 2, 3, 4]
    ],
    [
      [10, 12, 13, 14],
      [13, 14, 15, 16],
      [11, 13, 17, 19]
    ]
])
tensor

<tf.Tensor: shape=(2, 3, 4), dtype=int32, numpy=
array([[[ 1,  2,  3,  4],
        [10, 20, 30, 40],
        [ 1,  2,  3,  4]],

       [[10, 12, 13, 14],
        [13, 14, 15, 16],
        [11, 13, 17, 19]]], dtype=int32)>

In [25]:
# check the dimensions
tensor.ndim

3

## [2] Creating Tensors With `tf.Variable()`

In [19]:
# tensor of 1 dimension using tf.Variable()
variable_tensor = tf.Variable([10, 7])
variable_tensor

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10,  7], dtype=int32)>

In [30]:
# tensors created from tf.Variable() can be updated
# use the tf.assign() to update contents
variable_tensor[0].assign(-10)
variable_tensor[1].assign(-7)
variable_tensor

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([-10,  -7], dtype=int32)>

In [42]:
# variable tensor does not support direct asssignment
variable_tensor[1] = 70

TypeError: ignored

In [32]:
# tensor of 2 dimensions using tf.Variable()
variable_matrix = tf.Variable([
    [10, 20, 30],
    [1, 2, 3],
])
variable_matrix

<tf.Variable 'Variable:0' shape=(2, 3) dtype=int32, numpy=
array([[10, 20, 30],
       [ 1,  2,  3]], dtype=int32)>

In [35]:
# update the contents usng tf.assign()
variable_matrix[0].assign([-10, -20, -30])
variable_matrix

<tf.Variable 'Variable:0' shape=(2, 3) dtype=int32, numpy=
array([[-10, -20, -30],
       [  1,   2,   3]], dtype=int32)>

In [38]:
# cannot update different type using tf.assign()
variable_matrix[1].assign([1.123, 2.786, 3.1001])

TypeError: ignored

In [37]:
# cannot update a different shape using tf.assign()
variable_matrix[1].assign([23, 13])

UnimplementedError: ignored

In [39]:
# tensor created from tf.constant()
constant_tensor = tf.constant([10, 7])
constant_tensor

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10,  7], dtype=int32)>

In [40]:
# tensors created from tf.constant() cannot be updated using tf.assign()
constant_tensor[0].assign(-10)

AttributeError: ignored

In [41]:
# constant tensor created from tf.constant() cannot be updated by assignment
constant_tensor[0] = -10

TypeError: ignored

#### ❗Note

👉 In practice, we do not have to bother about `tf.constant` or `tf.Variable` as TensorFlow takes care of this for us  
👉 If the need arises, use `tf.constant`

## [3] Creating Random Tensors

Tensors of arbitrary size which contain random numbers. Very useful for initializing neural networks



In [43]:
# random tensors created with the same seed are equal
# the contents of individual tensors are random 
# all the tensors have the same random items
random_1 = tf.random.Generator.from_seed(42).normal(shape=(3, 2))
random_2 = tf.random.Generator.from_seed(42).normal(shape=(3, 2))

In [45]:
# check for equality
random_1 == random_2

<tf.Tensor: shape=(3, 2), dtype=bool, numpy=
array([[ True,  True],
       [ True,  True],
       [ True,  True]])>

In [46]:
random_1, random_2

(<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702],
        [ 0.07595026, -1.2573844 ],
        [-0.23193763, -1.8107855 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702],
        [ 0.07595026, -1.2573844 ],
        [-0.23193763, -1.8107855 ]], dtype=float32)>)

In [47]:
# random tensors created with different seed are not equal
# the contents of individual tensors are random
# the tensors have different random items
random1 = tf.random.Generator.from_seed(40).normal(shape=(3, 2))
random2 = tf.random.Generator.from_seed(10).normal(shape=(3, 2))

In [48]:
# check for equality
random1 == random2

<tf.Tensor: shape=(3, 2), dtype=bool, numpy=
array([[False, False],
       [False, False],
       [False, False]])>

In [49]:
random1, random2

(<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[ 0.78953624,  0.53897345],
        [-0.48535708,  0.74055266],
        [ 0.31662667, -1.4391748 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.29604465, -0.21134205],
        [ 0.01063002,  1.5165398 ],
        [ 0.27305737, -0.29925638]], dtype=float32)>)

### Shuffle The Order Of Elements In A Tensor

Very useful for neural networks - prevents the neural network from getting biassed from the inherent order of the data

In [50]:
tensor = tf.constant([
    [10, 7],
    [11, 13],
    [31, 37],
    [-4, 121]
])
tensor

<tf.Tensor: shape=(4, 2), dtype=int32, numpy=
array([[ 10,   7],
       [ 11,  13],
       [ 31,  37],
       [ -4, 121]], dtype=int32)>

In [51]:
# shuffle the tensor
tf.random.shuffle(tensor)

<tf.Tensor: shape=(4, 2), dtype=int32, numpy=
array([[ 31,  37],
       [ 10,   7],
       [ 11,  13],
       [ -4, 121]], dtype=int32)>

In [52]:
# shuffle the tensor 
tf.random.shuffle(tensor)

<tf.Tensor: shape=(4, 2), dtype=int32, numpy=
array([[ 10,   7],
       [ -4, 121],
       [ 11,  13],
       [ 31,  37]], dtype=int32)>

In [53]:
# original tensor is not modified - changes are not in-place
tensor

<tf.Tensor: shape=(4, 2), dtype=int32, numpy=
array([[ 10,   7],
       [ 11,  13],
       [ 31,  37],
       [ -4, 121]], dtype=int32)>

In [54]:
modified_tensor = tf.random.shuffle(tensor)
modified_tensor, tensor

(<tf.Tensor: shape=(4, 2), dtype=int32, numpy=
 array([[ 31,  37],
        [ -4, 121],
        [ 10,   7],
        [ 11,  13]], dtype=int32)>,
 <tf.Tensor: shape=(4, 2), dtype=int32, numpy=
 array([[ 10,   7],
        [ 11,  13],
        [ 31,  37],
        [ -4, 121]], dtype=int32)>)

❗ **PENDING_REVIEW**

In [65]:
# setting the seed ensures the same shuffle order
tf.random.set_seed(42) # set the global seed

tensor1 = tf.random.shuffle(tensor) # set the local seed 
tensor2 = tf.random.shuffle(tensor) # set the local seed
tensor3 = tf.random.shuffle(tensor) # set the local seed

In [66]:
tensor1, tensor2, tensor3

(<tf.Tensor: shape=(4, 2), dtype=int32, numpy=
 array([[ -4, 121],
        [ 10,   7],
        [ 11,  13],
        [ 31,  37]], dtype=int32)>,
 <tf.Tensor: shape=(4, 2), dtype=int32, numpy=
 array([[ 31,  37],
        [ 10,   7],
        [ -4, 121],
        [ 11,  13]], dtype=int32)>,
 <tf.Tensor: shape=(4, 2), dtype=int32, numpy=
 array([[ 10,   7],
        [ -4, 121],
        [ 11,  13],
        [ 31,  37]], dtype=int32)>)

In [67]:
some_tensor = tf.constant([
    [10, 9],
    [6, 19],
    [12, 3]
])
some_tensor

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[10,  9],
       [ 6, 19],
       [12,  3]], dtype=int32)>

In [71]:
tf.random.set_seed(7)

t1 = tf.random.shuffle(some_tensor, seed=42)
t2 = tf.random.shuffle(some_tensor, seed=42)
t3 = tf.random.shuffle(some_tensor, seed=42)

In [72]:
t1, t2, t3

(<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[10,  9],
        [12,  3],
        [ 6, 19]], dtype=int32)>, <tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[10,  9],
        [ 6, 19],
        [12,  3]], dtype=int32)>, <tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[ 6, 19],
        [10,  9],
        [12,  3]], dtype=int32)>)

## [4] Other Ways To Create Tensors

### Create Tensor Of All 1's 

In [73]:
ones = tf.ones(shape=(2, 4))
ones

<tf.Tensor: shape=(2, 4), dtype=float32, numpy=
array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]], dtype=float32)>

In [74]:
ones.ndim

2

### Create Tensor Of All 0's

In [75]:
zeros = tf.zeros(shape=(5, 1))
zeros

<tf.Tensor: shape=(5, 1), dtype=float32, numpy=
array([[0.],
       [0.],
       [0.],
       [0.],
       [0.]], dtype=float32)>

In [76]:
zeros.ndim

2

In [77]:
zeros = tf.zeros(shape=(5))
zeros

<tf.Tensor: shape=(5,), dtype=float32, numpy=array([0., 0., 0., 0., 0.], dtype=float32)>

In [78]:
zeros.ndim

1

### Create A Tensor From Numpy Array

The main difference between Tensorflow tensor and NumPy array is that tensors can run on GPU

In [82]:
# create a numpy array
A = np.arange(1, 25, dtype=np.int32)
A

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24], dtype=int32)

In [85]:
A.ndim

1

In [83]:
# convert to tensor
# default dimension of tensor is the same as that of numpy array
t = tf.constant(A)
t

<tf.Tensor: shape=(24,), dtype=int32, numpy=
array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24], dtype=int32)>

In [84]:
t.ndim

1

In [86]:
# to create a different dimension tensor from the array use shape parameter
# the value of shape must be the same as total number of elements
t1 = tf.constant(A, shape=(6, 4))
t2 = tf.constant(A, shape=(3, 4, 2))
t3 = tf.constant(A, shape=(24, 1))

In [87]:
t1, t2, t3

(<tf.Tensor: shape=(6, 4), dtype=int32, numpy=
 array([[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12],
        [13, 14, 15, 16],
        [17, 18, 19, 20],
        [21, 22, 23, 24]], dtype=int32)>,
 <tf.Tensor: shape=(3, 4, 2), dtype=int32, numpy=
 array([[[ 1,  2],
         [ 3,  4],
         [ 5,  6],
         [ 7,  8]],
 
        [[ 9, 10],
         [11, 12],
         [13, 14],
         [15, 16]],
 
        [[17, 18],
         [19, 20],
         [21, 22],
         [23, 24]]], dtype=int32)>,
 <tf.Tensor: shape=(24, 1), dtype=int32, numpy=
 array([[ 1],
        [ 2],
        [ 3],
        [ 4],
        [ 5],
        [ 6],
        [ 7],
        [ 8],
        [ 9],
        [10],
        [11],
        [12],
        [13],
        [14],
        [15],
        [16],
        [17],
        [18],
        [19],
        [20],
        [21],
        [22],
        [23],
        [24]], dtype=int32)>)

In [89]:
# create 2 dimensional numpy array
X = np.array([
    [10, 20, 30, 101],
    [50, 60, 70, 201]
])
X

array([[ 10,  20,  30, 101],
       [ 50,  60,  70, 201]])

In [90]:
X.shape, X.ndim

((2, 4), 2)

In [91]:
# convert to tensor
t = tf.constant(X)
t

<tf.Tensor: shape=(2, 4), dtype=int64, numpy=
array([[ 10,  20,  30, 101],
       [ 50,  60,  70, 201]])>

In [92]:
# default shape of tensor will be (2, 4)
# default dimension will be 2
t.shape, t.ndim

(TensorShape([2, 4]), 2)

In [97]:
t = tf.constant([
    [
      [1, 2, 3],
      [5, 6, 7],
      [9, 10, 11],
      [-1, -2, -3]
    ],
    [
      [10, 20, 30],
      [50, 60, 70],
      [19, 110, 111],
      [-1, -2, -3]
    ],
    [
      [105, 207, 390],
      [5034, 608, 7560],
      [1569, 11230, 1711],
      [-1, -20, -3]
    ]
], dtype=tf.int32)
t

<tf.Tensor: shape=(3, 4, 3), dtype=int32, numpy=
array([[[    1,     2,     3],
        [    5,     6,     7],
        [    9,    10,    11],
        [   -1,    -2,    -3]],

       [[   10,    20,    30],
        [   50,    60,    70],
        [   19,   110,   111],
        [   -1,    -2,    -3]],

       [[  105,   207,   390],
        [ 5034,   608,  7560],
        [ 1569, 11230,  1711],
        [   -1,   -20,    -3]]], dtype=int32)>

In [102]:
print(f"shape of tensor: {t.shape}")
print(f"rank of tensor: {t.ndim}")
print(f"dtype of tensor: {t.dtype}\n")

for i in range(t.ndim):
  print(f"shape of axis[{i}]: {t[i].shape}")
  print(f"rank of axis[{i}]: {t[i].ndim}")
  print(f"size of axis[{i}]: {tf.size(t[i])}\n")

print(f"size of tensor: {tf.size(t)}")

shape of tensor: (3, 4, 3)
rank of tensor: 3
dtype of tensor: <dtype: 'int32'>

shape of axis[0]: (4, 3)
rank of axis[0]: 2
size of axis[0]: 12

shape of axis[1]: (4, 3)
rank of axis[1]: 2
size of axis[1]: 12

shape of axis[2]: (4, 3)
rank of axis[2]: 2
size of axis[2]: 12

size of tensor: 36


# Working With Tensors



*   Indexing And Expanding 
*   Manipulating With Basic Operations
*   Matrix Multiplication
*   DataType Modifications
*   Aggregation Operations
*   Squeezing And One-Hot Encoding
*   Math Operations
*   Miscellaneous



## [1] Indexing And Expanding

In [1]:
tensor = tf.constant([
    [
      [1, 2, 3],
      [5, 6, 7],
      [9, 10, 11],
      [-1, -2, -3]
    ],
    [
      [10, 20, 30],
      [50, 60, 70],
      [19, 110, 111],
      [-1, -2, -3]
    ],
    [
      [105, 207, 390],
      [5034, 608, 7560],
      [1569, 11230, 1711],
      [-1, -20, -3]
    ]
], dtype=tf.int32)
tensor

NameError: ignored

In [134]:
# get the first two elements of each dimension
tensor[0, :2, :3]

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[1, 2, 3],
       [5, 6, 7]], dtype=int32)>